# --- Font Settings ---
font_family      RobotoMono Nerd Font
font_size        10.0

# --- Window Size ---
# The 'c' suffix tells kitty to use cells (columns/rows) instead of pixels
initial_window_width   130c
initial_window_height  36c

# --- Color Theme (Red on Black) ---
background   #000000
foreground   #BDBDBD
cursor       #ff0000
cursor_text_color #000000

# --- Transparency and Blur ---
background_opacity .25
background_blur 15
